### ISSUE TITLE
Error case 

### ISSUE THREAD

**Issue by dav1d-b** [alChaCC/easy-box-packer#7]
```
container = EasyBoxPacker.find_smallest_container(
items:  [
            { dimensions: [57.0, 47.0, 73.0], weight: 0 },
            { dimensions: [15.3, 15.3, 15.3], weight: 0 },
        ]   
  )
```

This code produces error:

```
from /gems/easy-box-packer-0.0.8/easy-box-packer.rb:100:in `find_smallest_container'
/home/david/gems/gems/easy-box-packer-0.0.8/easy-box-packer.rb:445:in `check_container_is_bigger_than_greedy_box': undefined method `>=' for [57.0, 62.3, 73.0]:Array (NoMethodError)
```

**Comment by eyalabadi98** [comment]
@daviddzxy For the smallest container, remove the weight element as it will give you an error. That fixed it
